/**********************************************************
 * This file is generated by 20-sim ANSI-C Code Generator
 *
 *  file:  xxmodel.c
 *  model: PositionControllerPan
 *  expmt: 20-1E73
 *  date:  June 16, 2017
 *  time:  5:49:45 PM
 *  user:  Universiteit Twente
 *  from:  20-sim 4.6 Campus Licentie
 *  build: 4.6.3.7733
 **********************************************************/

/* This file contains the actual model variables and equations */

/* Note: Alias variables are the result of full optimization
   of the model in 20-sim. As a result, only the real variables
   are used in the model for speed. The user may also include
   the alias variables by adding them to the end of the array:

   XXDouble xx_variables[NUMBER_VARIABLES + NUMBER_ALIAS_VARIABLES + 1];
   XXCharacter *xx_variable_names[] = {
     VARIABLE_NAMES, ALIAS_VARIABLE_NAMES, NULL
   };

   and calculate them directly after the output equations:

   void XXCalculateOutput (void)
   {
     OUTPUT_EQUATIONS
     ALIAS_EQUATIONS
   }
*/

/* system include files */
#include <stdlib.h>
#include <math.h>

/* 20-sim include files */
#include "xxmodel.h"
#include "xxfuncs.h"
#include "xxmatrix.h"


/* the global variables */
XXDouble xx_start_time = 0.0;
XXDouble xx_finish_time = 20.0;
XXDouble xx_step_size = 0.01;
XXDouble xx_time;
XXInteger xx_steps;
XXBoolean xx_initialize;
XXBoolean xx_major = XXTRUE;
XXBoolean xx_stop_simulation = XXFALSE;

/* the variable arrays */
XXDouble xx_C[0 + 1];		/* constants */
XXDouble xx_P[7 + 1];		/* parameters */
XXDouble xx_I[3 + 1];		/* initial values */
XXDouble xx_V[10 + 1];		/* variables */
XXDouble xx_s[3 + 1];		/* states */
XXDouble xx_R[3 + 1];		/* rates (or new states) */
XXMatrix xx_M[0 + 1];		/* matrices */
XXDouble xx_U[0 + 1];		/* unnamed */
XXDouble xx_workarray[0 + 1];
XXDouble xx_F[0 + 1];	/* favorite parameters */
XXDouble xx_f[0 + 1];		/* favorite variables */

/* the names of the variables as used in the arrays above
   uncomment this part if these names are needed
XXCharacter *xx_constant_names[] = {
	NULL,	NULL
};
XXCharacter *xx_parameter_names[] = {
	"corrGain\\K",
	"PID1\\kp",
	"PID1\\tauD",
	"PID1\\beta",
	"PID1\\tauI",
	"SignalLimiter2\\minimum",
	"SignalLimiter2\\maximum"
,	NULL
};
XXCharacter *xx_initial_value_names[] = {
	"PID1\\uD_previous_initial",
	"PID1\\error_previous_initial",
	"PID1\\uI_previous_initial"
,	NULL
};
XXCharacter *xx_variable_names[] = {
	"corrGain\\corr",
	"PID1\\output",
	"",
	"PlusMinus1\\plus1",
	"SignalLimiter2\\output",
	"Splitter1\\input",
	"corr",
	"in",
	"position",
	"out"
,	NULL
};
XXCharacter *xx_state_names[] = {
	"PID1\\uD_previous",
	"PID1\\error_previous",
	"PID1\\uI_previous"
,	NULL
};
XXCharacter *xx_rate_names[] = {
	"",
	"PID1\\error",
	""
,	NULL
};
XXCharacter *xx_matrix_names[] = {
	NULL
,	NULL
};
XXString xx_favorite_par_names[] = {
	NULL, NULL
};
XXString xx_favorite_var_names[] = {
	NULL, NULL
};
*/

/* this method is called before calculation is possible */
void XXModelInitialize (void)
{
	/* set the constants */


	/* set the parameters */
	xx_P[0] = 0.0;		/* corrGain\K */
	xx_P[1] = 2.6;		/* PID1\kp */
	xx_P[2] = 0.05;		/* PID1\tauD */
	xx_P[3] = 0.17;		/* PID1\beta */
	xx_P[4] = 9.0;		/* PID1\tauI */
	xx_P[5] = -0.99;		/* SignalLimiter2\minimum */
	xx_P[6] = 0.99;		/* SignalLimiter2\maximum */


	/* set the initial values */
	xx_I[0] = 0.0;		/* PID1\uD_previous_initial */
	xx_I[1] = 0.0;		/* PID1\error_previous_initial */
	xx_I[2] = 0.0;		/* PID1\uI_previous_initial */


	/* set the states */
	xx_s[0] = xx_I[0];		/* PID1\uD_previous */
	xx_s[1] = xx_I[1];		/* PID1\error_previous */
	xx_s[2] = xx_I[2];		/* PID1\uI_previous */


	/* set the matrices */


	/* set the favorites */


}

/* This function calculates the initial equations of the model.
 * These equations are calculated before anything else
 */
void XXCalculateInitial (void)
{
	/* the favorite parameters equations */



}

/* This function calculates the static equations of the model.
 * These equations are only dependent from parameters and constants
 */
void XXCalculateStatic (void)
{

}

/* This function calculates the input equations of the model.
 * These equations are dynamic equations that must not change
 * in calls from the integration method (like random and delay).
 */
void XXCalculateInput (void)
{
	/* the favorite parameters equations */



}

/* This function calculates the dynamic equations of the model.
 * These equations are called from the integration method
 * to calculate the new model rates (that are then integrated).
 */
void XXCalculateDynamic (void)
{
	/* PID1\factor = 1 / (sampletime + PID1\tauD * PID1\beta); */
	xx_V[2] = 1.0 / (xx_step_size + xx_P[2] * xx_P[3]);

	/* PlusMinus1\plus1 = in; */
	xx_V[3] = xx_V[7];

	/* Splitter1\input = position; */
	xx_V[5] = xx_V[8];

	/* corrGain\corr = corrGain\K * Splitter1\input; */
	xx_V[0] = xx_P[0] * xx_V[5];

	/* PID1\error = PlusMinus1\plus1 - Splitter1\input; */
	xx_R[1] = xx_V[3] - xx_V[5];

	/* PID1\uD = PID1\factor * (((PID1\tauD * PID1\uD_previous) * PID1\beta + (PID1\tauD * PID1\kp) * (PID1\error - PID1\error_previous)) + (sampletime * PID1\kp) * PID1\error); */
	xx_R[0] = xx_V[2] * (((xx_P[2] * xx_s[0]) * xx_P[3] + (xx_P[2] * xx_P[1]) * (xx_R[1] - xx_s[1])) + (xx_step_size * xx_P[1]) * xx_R[1]);

	/* PID1\uI = PID1\uI_previous + (sampletime * PID1\uD) / PID1\tauI; */
	xx_R[2] = xx_s[2] + (xx_step_size * xx_R[0]) / xx_P[4];

	/* PID1\output = PID1\uI + PID1\uD; */
	xx_V[1] = xx_R[2] + xx_R[0];

	/* SignalLimiter2\output = (if PID1\output < SignalLimiter2\minimum then SignalLimiter2\minimum else (if PID1\output > SignalLimiter2\maximum then SignalLimiter2\maximum else PID1\output end) end); */
	xx_V[4] = ((xx_V[1] < xx_P[5]) ? 
		/* SignalLimiter2\minimum */
		xx_P[5]
	:
		/* (if PID1\output > SignalLimiter2\maximum then SignalLimiter2\maximum else PID1\output end) */
		((xx_V[1] > xx_P[6]) ? 
			/* SignalLimiter2\maximum */
			xx_P[6]
		:
			/* PID1\output */
			xx_V[1]
		)
	);


	/* increment the step counter */
	xx_steps++;
}

/* This function calculates the output equations of the model.
 * These equations are not needed for calculation of the rates
 * and are kept separate to make the dynamic set of equations smaller.
 * These dynamic equations are called often more than one time for each
 * integration step that is taken. This makes model computation much faster.
 */
void XXCalculateOutput (void)
{
	/* corr = corrGain\corr; */
	xx_V[6] = xx_V[0];

	/* out = SignalLimiter2\output; */
	xx_V[9] = xx_V[4];


	/* set the favorite variables */

}

/* This function calculates the final equations of the model.
 * These equations are calculated after all the calculations
 * are performed
 */
void XXCalculateFinal (void)
{

}

/* this method is called after all calculations are performed */
void XXModelTerminate(void)
{
}

